name: conditional workflow

on:
  push:
    paths: -"backend/***"
jobs:
  conditional-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Build onlybackend images
        run: echo ""Build only condicational workflows"
