name: Conditional Workflow

on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Build only backend images
        run: echo "Build only conditional workflows"
