name: predefined workflows

on:
  push:
    branches: [main]

jobs:
  predefined-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Nodejs version check
        run: node -v

      - name: new update node js
        uses: actions/setup-node@v2
        with:
          node-version: "24"

      - name: Nodejs version check 2
        run: node -v
